{
 "title": "datascience_RagBot",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval),\n  SUM(total_tokens) as \"Total Tokens\"\nFROM conversations\nWHERE $__timeFilter(timestamp)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "OpenAI Cost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval),\n  SUM(openai_cost) as \"OpenAI Cost\"\nFROM conversations\nWHERE $__timeFilter(timestamp)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Relevance",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  AVG(CASE \n    WHEN relevance = 'RELEVANT' THEN 10\n    WHEN relevance = 'PARTLY_RELEVANT' THEN 5\n    ELSE 0 \n  END) as relevancy_score\nFROM conversations\nWHERE timestamp > $__timeFrom() AND timestamp < $__timeTo()"
    }
   ]
  },
  {
   "title": "+1/-1",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  SUM(CASE WHEN feedback > 0 THEN 1 ELSE 0 END) as thumbs_up,\n  SUM(CASE WHEN feedback < 0 THEN 1 ELSE 0 END) as thumbs_down\nFROM feedback"
    }
   ]
  },
  {
   "title": "Last 5 conversations",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT \n  timestamp as time,\n  question,\n  answer,\n  relevance\nFROM conversations\nORDER BY timestamp DESC\nLIMIT 5"
    },
    {
     "rawSql": "SELECT\n    SUM(CASE WHEN feedback > 0 THEN 1 ELSE 0 END) as positive,\n    SUM(CASE WHEN feedback < 0 THEN 1 ELSE 0 END) as negative,\n    SUM(CASE WHEN feedback = 0 THEN 1 ELSE 0 END) as neutral\nFROM feedback;"
    }
   ]
  }
 ]
}